### ISSUE TITLE
Not compatible with angular-material 0.10.1

### ISSUE THREAD

**Issue by kevin-abl** [Soopro/ng-material-dropmenu#6]
Works fine with 0.10.0, but with 0.10.1, if I click on a menu option, it locks up the whole app.  If this isn't reproducible for you, please reach out to me and I'll provide the details you need.

Cheers and thanks!

**Comment by redyyu** [comment]
0.10.0 must have official drop menu, you better switch to the official version.
the reason I made this is because 0.9.x don't have menu.

My project still using 0.9.4rc. that's why I never testing in 0.10.0.
